{
 "title": "Rundek",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "rundeck_host", "label": "rundeck_url", "query": "${VAR_RUNDECK_HOST}" }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_uptime_since{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_api_requests_requestTimer_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Web Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(rundeck_api_requests_requestTimer_total{instance=\"$instance\"} - rundeck_web_requests_requestTimer_total{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_threadPoolSize{instance=\"$instance\"}",
     "legendFormat": "Thread Pool Size"
    },
    {
     "expr": "rundeck_system_stats_threads_active{instance=\"$instance\"}",
     "legendFormat": "Threads active"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((rundeck_system_stats_memory_total_bytes{instance=\"${instance}\"} - rundeck_system_stats_memory_free_bytes{instance=\"${instance}\"}) / rundeck_system_stats_memory_total_bytes{instance=\"${instance}\"})*100",
     "legendFormat": "memory"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Job success rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(topk(1,last_over_time(rundeck_project_execution_status{status=\"succeeded\", instance=~\"${instance}\"}[$__range])) by(execution_id, job_id))  / sum(topk(1,last_over_time(rundeck_project_execution_status[$__range])) by(execution_id, job_id)))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of executed jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\"}[$__range])) by(execution_id, job_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_scheduler_quartz_scheduledJobs{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Job execution duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(1,last_over_time(rundeck_project_execution_duration_seconds[$__range])) by(execution_id) * on (execution_id) group_left(status) topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\"}[$__range])) by(execution_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_running{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Job count ( by status )",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\"}[$__range])) by(execution_id, job_id)) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Count ( by job_name )",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\"}[$__range])) by(execution_id, job_id)) by(job_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job count ( by user )",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(count(topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\"}[$__range])) by(execution_id, job_id)) by(user))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed jobs count( by job_name )",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\",status=\"failed\"}[$__range])) by(execution_id, job_id)) by(job_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job execution duration",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(1,last_over_time(rundeck_project_execution_duration_seconds[$__range])) by(execution_id) * on (execution_id) group_left(status) topk(1,last_over_time(rundeck_project_execution_status{instance=~\"${instance}\"}[$__range])) by(execution_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}